#ifndef __THERMOGRAM_H__
#define __THERMOGRAM_H__

#include "rjpg_header.h"
#include "dtv_header.h"

#define        TH_UNSET  0x0    ///< default value
#define    TH_IRTIS_DTV  0x1    ///< images generated by an IRTIS 2000 camera
#define    TH_FLIR_RJPG  0x2    ///< radiometric jpeg images generated by a Flir camera

#define     TH_DTV_VER2  0x2
#define     TH_DTV_VER3  0x3

#define     TH_FLIR_THERMACAM_E25  0x1
#define                TH_FLIR_E5  0x2

#define          ID_THERMACAM_E25  "ThermaCAM  E25"
#define                ID_FLIR_E5  "FLIR E5"

struct tgram {
    uint16_t type;      ///< thermogram type
    uint16_t subtype;   ///< thermography model identifier
    union head_t {
        dtv_header_t *dtv;      ///< pointer to a DTV header
        rjpg_header_t *rjpg;    ///< pointer to a rjpeg header
    } head;
    uint8_t *frame;     ///< raw thermal data (if information is 8bit per pixel)
    uint16_t *framew;   ///< raw thermal data (if information is 16bit per pixel)
};

typedef struct tgram tgram_t;

#endif

